// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportResults(arg1, arg2) {
  return window['go']['main']['App']['ExportResults'](arg1, arg2);
}

export function RunTest(arg1) {
  return window['go']['main']['App']['RunTest'](arg1);
}

export function SendTestMail(arg1, arg2) {
  return window['go']['main']['App']['SendTestMail'](arg1, arg2);
}
