// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {smtp} from '../models';

export function ExportResults(arg1:Array<smtp.TestResult>,arg2:string):Promise<string>;

export function RunTest(arg1:smtp.SMTPConfig):Promise<Array<smtp.TestResult>>;

export function SendTestMail(arg1:smtp.SMTPConfig,arg2:string):Promise<smtp.TestResult>;
